name: onedrive_api
description: OneDrive API module for Flutter and Dart.
version: 1.0.0
repository: https://github.com/alvi-khan/onedrive_api

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
