name: onedrive_api
description: OneDrive API module for Flutter and Dart.
version: 0.2.0
repository: https://github.com/alvi-khan/onedrive_api

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.1.0
  test: ^1.24.0
